server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: order-fegin

redis:
  hostName: 127.0.0.1
  pool:
    maxActive: 8
    maxIdle: 8
    maxWait: -1
    minIdle: 0
  port: 6379
  timeout: 0

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000