server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-merchant


  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.125:8066/PROJECT?ServerTimezone=HongKong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mybatis/*.xml

redis:
  hostName: 127.0.0.1
  pool:
    maxActive: 8
    maxIdle: 8
    maxWait: -1
    minIdle: 0
  port: 6379
  timeout: 0






