server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-merchant
    name: spring-provider


  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/takeout-project?ServerTimezone=HongKong&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:8066/PROJECT?ServerTimezone=HongKong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mybatis/*.xml



